# Generated by Django 3.0.7 on 2020-07-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='review text')),
                ('pub_date', models.DateTimeField(verbose_name='publication date')),
                ('author_name', models.CharField(max_length=50, verbose_name="author's name")),
            ],
        ),
    ]
